### ISSUE TITLE
Bugged scroll behavior if ReverseEmoteWheelScrollDirection enabled

### ISSUE THREAD

**Issue by afisarsy** [cmooref17/Lethal-Company-TooManyEmotes#21]
If you set ReverseEmoteWheelScrollDirection to True, scroll up and scroll down both will change to the next emote wheel set, you can't scroll to the previous emote wheel set.

**Comment by cmooref17** [comment]
I want to say this has been fixed now. Could you let me know if not?

**Comment by cmooref17** [comment]
If this hasn't been fixed, please reopen this ticket!

**Comment by afisarsy** [comment]
Nope, still not working, it's still go to the next wheel set wether I scroll up or down if ```ReverseEmoteWheelScrollDirection``` is set to True
